# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase-if-necessary
    cooldown:
      default-days: 4
    ignore:
      # We currently support only v3 of Bootstrap. Prevent PRs for v4.0.0 or higher.
      # See https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/secure-your-dependencies/configure-version-updates
      - dependency-name: "bootstrap"
        versions: [">= 4.0.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 4
