import { StatisticsData } from "../../src/interfaces";

export const testLibraryKey = "lyrasis-reads";
export const noCollectionsLibraryKey = "unfunded-library";
export const noInventoryLibraryKey = "unfunded-library";
export const noPatronsLibraryKey = "unused-library";
export const statisticsApiResponseData: StatisticsData = {
  collections: [
    {
      id: 7,
      name: "TEST Palace Marketplace",
      inventory: {
        titles: 7753,
        lendable: 7750,
        selfHosted: 0,
        openAccess: 0,
        licensed: 7753,
        unlimitedLicense: 0,
        meteredLicense: 7753,
        meteredLicensesOwned: 305725,
        meteredLicensesAvailable: 75337,
      },
    },
    {
      id: 8,
      name: "TEST OverDrive",
      inventory: {
        titles: 4441,
        lendable: 4436,
        selfHosted: 0,
        openAccess: 0,
        licensed: 4441,
        unlimitedLicense: 0,
        meteredLicense: 4441,
        meteredLicensesOwned: 4072997338,
        meteredLicensesAvailable: 4072997325,
      },
    },
    {
      id: 9,
      name: "New Bibliotheca Test Collection",
      inventory: {
        titles: 76,
        lendable: 64,
        selfHosted: 0,
        openAccess: 0,
        licensed: 76,
        unlimitedLicense: 0,
        meteredLicense: 76,
        meteredLicensesOwned: 85,
        meteredLicensesAvailable: 72,
      },
    },
    {
      id: 14,
      name: "New BiblioBoard Test",
      inventory: {
        titles: 13306,
        lendable: 13306,
        selfHosted: 0,
        openAccess: 0,
        licensed: 13306,
        unlimitedLicense: 0,
        meteredLicense: 13306,
        meteredLicensesOwned: 13306,
        meteredLicensesAvailable: 13306,
      },
    },
    {
      id: 16,
      name: "TEST Baker & Taylor",
      inventory: {
        titles: 146,
        lendable: 134,
        selfHosted: 0,
        openAccess: 0,
        licensed: 146,
        unlimitedLicense: 0,
        meteredLicense: 146,
        meteredLicensesOwned: 147,
        meteredLicensesAvailable: 135,
      },
    },
    {
      id: 17,
      name: "A1QA Palace Marketplace",
      inventory: {
        titles: 7753,
        lendable: 7750,
        selfHosted: 0,
        openAccess: 0,
        licensed: 7753,
        unlimitedLicense: 0,
        meteredLicense: 7753,
        meteredLicensesOwned: 305730,
        meteredLicensesAvailable: 75341,
      },
    },
    {
      id: 18,
      name: "CALIFA Enki Test",
      inventory: {
        titles: 93239,
        lendable: 91565,
        selfHosted: 0,
        openAccess: 0,
        licensed: 93239,
        unlimitedLicense: 0,
        meteredLicense: 93239,
        meteredLicensesOwned: 7957965,
        meteredLicensesAvailable: 7955952,
      },
    },
    {
      id: 19,
      name: "Palace Bookshelf",
      inventory: {
        titles: 7838,
        lendable: 7838,
        selfHosted: 0,
        openAccess: 7838,
        licensed: 0,
        unlimitedLicense: 0,
        meteredLicense: 0,
        meteredLicensesOwned: 0,
        meteredLicensesAvailable: 0,
      },
    },
    {
      id: 20,
      name: "Test ProQuest OPDS 2",
      inventory: {
        titles: 1575,
        lendable: 1575,
        selfHosted: 0,
        openAccess: 0,
        licensed: 1575,
        unlimitedLicense: 1575,
        meteredLicense: 0,
        meteredLicensesOwned: 0,
        meteredLicensesAvailable: 0,
      },
    },
  ],
  libraries: [
    {
      key: "lyrasis-reads",
      name: "LYRASIS Reads",
      patronStatistics: {
        total: 132,
        withActiveLoan: 21,
        withActiveLoanOrHold: 23,
        loans: 87,
        holds: 5,
      },
      inventorySummary: {
        titles: 29119,
        lendable: 29092,
        selfHosted: 145,
        openAccess: 7838,
        licensed: 21281,
        unlimitedLicense: 623,
        meteredLicense: 20658,
        meteredLicensesOwned: 319263,
        meteredLicensesAvailable: 88850,
      },
      collectionIds: [7, 9, 14, 16, 19],
    },
    {
      key: "announcements-test",
      name: "Announcements Testing",
      patronStatistics: {
        total: 2,
        withActiveLoan: 0,
        withActiveLoanOrHold: 0,
        loans: 0,
        holds: 0,
      },
      inventorySummary: {
        titles: 0,
        lendable: 0,
        selfHosted: 0,
        openAccess: 0,
        licensed: 0,
        unlimitedLicense: 0,
        meteredLicense: 0,
        meteredLicensesOwned: 0,
        meteredLicensesAvailable: 0,
      },
      collectionIds: [],
    },
    {
      key: "qa1223",
      name: "Test Library for QA",
      patronStatistics: {
        total: 1,
        withActiveLoan: 0,
        withActiveLoanOrHold: 0,
        loans: 0,
        holds: 0,
      },
      inventorySummary: {
        titles: 7753,
        lendable: 7750,
        selfHosted: 0,
        openAccess: 0,
        licensed: 7753,
        unlimitedLicense: 0,
        meteredLicense: 7753,
        meteredLicensesOwned: 305725,
        meteredLicensesAvailable: 75337,
      },
      collectionIds: [7],
    },
    {
      key: "od-test",
      name: "Overdrive Integration Test",
      patronStatistics: {
        total: 3,
        withActiveLoan: 0,
        withActiveLoanOrHold: 0,
        loans: 0,
        holds: 0,
      },
      inventorySummary: {
        titles: 4441,
        lendable: 4436,
        selfHosted: 0,
        openAccess: 0,
        licensed: 4441,
        unlimitedLicense: 0,
        meteredLicense: 4441,
        meteredLicensesOwned: 4072997338,
        meteredLicensesAvailable: 4072997325,
      },
      collectionIds: [8],
    },
    {
      key: "unused-library",
      name: "The Unused Library",
      patronStatistics: {
        total: 0,
        withActiveLoan: 0,
        withActiveLoanOrHold: 0,
        loans: 0,
        holds: 0,
      },
      inventorySummary: {
        titles: 33560,
        lendable: 33528,
        selfHosted: 0,
        openAccess: 7838,
        licensed: 25722,
        unlimitedLicense: 0,
        meteredLicense: 25722,
        meteredLicensesOwned: 4073316601,
        meteredLicensesAvailable: 4073086175,
      },
      collectionIds: [7, 8, 9, 14, 16, 19],
    },
    {
      key: "a1qa-test",
      name: "A1QA Test Library",
      patronStatistics: {
        total: 7,
        withActiveLoan: 0,
        withActiveLoanOrHold: 0,
        loans: 0,
        holds: 0,
      },
      inventorySummary: {
        titles: 107230,
        lendable: 105524,
        selfHosted: 0,
        openAccess: 0,
        licensed: 107230,
        unlimitedLicense: 1575,
        meteredLicense: 105655,
        meteredLicensesOwned: 4081261265,
        meteredLicensesAvailable: 4081028825,
      },
      collectionIds: [8, 9, 16, 17, 18, 20],
    },
    {
      key: "unfunded-library",
      name: "The Unfunded Public Library",
      patronStatistics: {
        total: 0,
        withActiveLoan: 0,
        withActiveLoanOrHold: 0,
        loans: 0,
        holds: 0,
      },
      inventorySummary: {
        titles: 0,
        lendable: 0,
        selfHosted: 0,
        openAccess: 0,
        licensed: 0,
        unlimitedLicense: 0,
        meteredLicense: 0,
        meteredLicensesOwned: 0,
        meteredLicensesAvailable: 0,
      },
      collectionIds: [],
    },
  ],
  inventorySummary: {
    titles: 136127,
    lendable: 134418,
    selfHosted: 0,
    openAccess: 7838,
    licensed: 128289,
    unlimitedLicense: 1575,
    meteredLicense: 126714,
    meteredLicensesOwned: 4081580296,
    meteredLicensesAvailable: 4081117468,
  },
  patronSummary: {
    total: 145,
    withActiveLoan: 0,
    withActiveLoanOrHold: 4,
    loans: 0,
    holds: 5,
  },
};
