name: Sync branch with NYPL
on:
  schedule:
    - cron:  '0 7 * * *'

  workflow_dispatch:

jobs:
  sync_with_nypl:
    runs-on: ubuntu-latest

    env:
      UPSTREAM_ORG: NYPL-Simplified
      UPSTREAM_REPO: circulation-web
      UPSTREAM_BRANCH: main
      ORIGIN_BRANCH: nypl/main

    steps:
      - name: Checkout repo to sync
        uses: actions/checkout@v3
        with:
          path: code

      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: 'ThePalaceProject/ci-scripts'
          path: ci

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Python requirements
        run: pip install -r ci/sync-requirements.txt

      - name: Sync branch with upstream
        run: python ci/sync.py code
